[tool.poetry]
name = "ol-dags"
version = "0.1.0"
description = "Data pipelines for open learning"
authors = ["Tobias Macey"]
license = "BSD-3-Clause"

[tool.poetry.dependencies]
python = "^3.8"
dagster = "^0.7.3"
dagit = "^0.7.3"
great-expectations = "^0.9.3"
dagster-aws = "^0.7.3"
dagster-postgres = "^0.7.3"
pypika = "^0.36.0"
httpx = "^0.12.0"
pymysql = "^0.9.3"

[tool.poetry.dev-dependencies]
wemake-python-styleguide = "^0.13.4"
pytest = "^5.3.5"
mypy = "^0.770"
isort = "^4.3.21"
pre-commit = "^2.3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
